# Global settings applicable across multiple components
replicaCount: 1

image:
  repository: hamid009/go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "325f68e8bca02132898dcf10c95f2fbd9c6d010e"
