# Global settings applicable across multiple components
replicaCount: 1

image:
  repository: hamid009/go-web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "b4a52e3c977e4d2ea7b5681f4c6c40014386b61b"
